//! S12 auth-service error type: `AUT-xxx` codes with the standard envelope
//! mapping (CONVENTIONS §1.1 / §1.2 / §1.4).
//!
//! Ranges: `AUT-0xx` protocol/boot, `AUT-1xx` config/key-generation,
//! `AUT-2xx` request / token validation.

use crate::json::Value;

/// Every error the auth service can produce, carrying the envelope triple
/// `(code, message, retryable)` plus an HTTP status and debug context.
#[derive(Debug, Clone, PartialEq)]
pub struct AuthError {
    pub code: &'static str,
    pub message: String,
    pub status: u16,
    pub retryable: bool,
    pub context: Value,
}

impl AuthError {
    fn new(code: &'static str, status: u16, retryable: bool, message: String, context: Value) -> Self {
        Self { code, message, status, retryable, context }
    }

    /// AUT-001: protocol-level failure (bad request line, oversized body, ...).
    /// Generated by the template server itself, not by a handler.
    pub fn protocol(detail: &str) -> Self {
        Self::new("AUT-001", 400, false, format!("Protocol error: {}", detail),
            Value::object(vec![]))
    }

    /// AUT-002: no route matches method+path.
    pub fn no_route(method: &str, path: &str) -> Self {
        Self::new("AUT-002", 404, false, "No such route.".to_string(),
            Value::object(vec![
                ("method", Value::from(method.to_string())),
                ("path", Value::from(path.to_string())),
            ]))
    }

    /// AUT-003: path exists but the method is not allowed.
    pub fn method_not_allowed(allowed: &[&'static str]) -> Self {
        let list: Vec<Value> = allowed.iter().map(|m| Value::from(*m)).collect();
        Self::new("AUT-003", 405, false, "Method not allowed.".to_string(),
            Value::object(vec![("allowed", Value::from(list))]))
    }

    /// AUT-100: configuration failed validation at boot.
    pub fn config_invalid(detail: &str) -> Self {
        Self::new("AUT-100", 500, false, format!("Invalid configuration: {}", detail),
            Value::object(vec![]))
    }

    /// AUT-101: /dev/urandom key generation failed (transient).
    pub fn key_generation_failed(detail: &str) -> Self {
        Self::new("AUT-101", 500, true, format!("Key generation failed: {}", detail),
            Value::object(vec![]))
    }

    /// AUT-201: request body is not valid JSON or of the wrong shape.
    pub fn malformed_body(detail: &str) -> Self {
        Self::new("AUT-201", 400, false, format!("Malformed request body: {}", detail),
            Value::object(vec![]))
    }

    /// AUT-202: `sub` is missing, empty, or not a string (POST /token).
    pub fn missing_subject(detail: &str) -> Self {
        Self::new("AUT-202", 400, false,
            format!("'sub' is required and must be a non-empty string: {}", detail),
            Value::object(vec![]))
    }

    /// AUT-203: `ttl_ns` override is out of range (POST /token).
    pub fn bad_ttl(detail: &str) -> Self {
        Self::new("AUT-203", 400, false, format!("Invalid ttl_ns: {}", detail),
            Value::object(vec![]))
    }

    /// AUT-204: token is not a 3-segment base64url compact JWT.
    pub fn malformed_token(detail: &str) -> Self {
        Self::new("AUT-204", 400, false, format!("Malformed token: {}", detail),
            Value::object(vec![]))
    }

    /// AUT-205: header `alg` is not HS256.
    pub fn bad_algorithm(alg: &str) -> Self {
        Self::new("AUT-205", 400, false, format!("Unsupported algorithm: {}", alg),
            Value::object(vec![]))
    }

    /// AUT-206: header `kid` is not in the key ring.
    pub fn unknown_key(kid: &str) -> Self {
        Self::new("AUT-206", 400, false, format!("Unknown key id: {}", kid),
            Value::object(vec![]))
    }

    /// AUT-207: HMAC over `header.payload` does not match the signature.
    pub fn bad_signature(kid: &str) -> Self {
        Self::new("AUT-207", 400, false, format!("Signature mismatch for key {}", kid),
            Value::object(vec![]))
    }

    /// AUT-208: token is past its `exp` (skew applied).
    pub fn expired(exp: i64, now: i64) -> Self {
        Self::new("AUT-208", 400, false, "Token is expired.".to_string(),
            Value::object(vec![
                ("exp", Value::from(exp)),
                ("now", Value::from(now)),
            ]))
    }

    /// AUT-209: token's `nbf` is in the future (skew applied).
    pub fn not_yet_valid(nbf: i64, now: i64) -> Self {
        Self::new("AUT-209", 400, false, "Token is not yet valid.".to_string(),
            Value::object(vec![
                ("nbf", Value::from(nbf)),
                ("now", Value::from(now)),
            ]))
    }

    /// AUT-210: `jti` is in the revocation set.
    pub fn revoked(jti: &str) -> Self {
        Self::new("AUT-210", 400, false, "Token has been revoked.".to_string(),
            Value::object(vec![("jti", Value::from(jti.to_string()))]))
    }

    /// AUT-211: a required scope is absent from the token.
    pub fn missing_scope(required: &str) -> Self {
        Self::new("AUT-211", 400, false, format!("Required scope missing: {}", required),
            Value::object(vec![]))
    }

    /// AUT-212: claim semantics failed (issuer, subject, time ordering).
    pub fn semantic_mismatch(detail: &str) -> Self {
        Self::new("AUT-212", 400, false, format!("Semantic mismatch: {}", detail),
            Value::object(vec![]))
    }

    /// AUT-213: `jti` is missing or empty (POST /revoke).
    pub fn missing_jti() -> Self {
        Self::new("AUT-213", 400, false,
            "'jti' is required and must be a non-empty string.".to_string(),
            Value::object(vec![]))
    }

    /// AUT-214: `token` is missing or empty (POST /verify).
    pub fn missing_token() -> Self {
        Self::new("AUT-214", 400, false,
            "'token' is required and must be a non-empty string.".to_string(),
            Value::object(vec![]))
    }

    /// HTTP status for this error.
    pub fn status(&self) -> u16 {
        self.status
    }

    /// Envelope error code, e.g. `"AUT-207"`.
    pub fn code(&self) -> &'static str {
        self.code
    }

    /// Human-readable single-sentence message.
    pub fn message(&self) -> &str {
        &self.message
    }

    /// Whether the caller should retry with backoff.
    pub fn retryable(&self) -> bool {
        self.retryable
    }

    /// Structured debug context (an object, possibly empty).
    pub fn context(&self) -> &Value {
        &self.context
    }
}

impl std::fmt::Display for AuthError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.code, self.message)
    }
}

impl std::error::Error for AuthError {}
